name: Landlord
main: com.jcdesimp.landlord.Landlord
version: 0.1
author: Jcdesimp
authors: []
website: http://dev.bukkit.org/bukkit-plugins/landlord/

softdepend: [Vault, WorldGuard]

commands:
   landlord:
      aliases: [land, ll]
      description: The base Landlord command.
      usage: /<command> [player]
      permission: <plugin name>.player.*
      permission-message: You don't have <permission>

permissions:

    landlord.*:
        description: Gives access to all landlord commands
        children:
            landlord.player.*: true
            landlord.admin.*: true

    landlord.player.*:
            description: Gives access to default player commands.
            children:
                landlord.player.own: true

    landlord.admin.*:
        description: Gives access to admin commands.
        children:
            landlord.admin.unclaim: true
            landlord.admin.list: true
            landlord.admin.manage: true
            landlord.admin.clearWorld: true


    landlord.admin.unclaim:
        description: Unclaim any land
        default: op
    landlord.admin.list:
        description: list all land owned by a user
        default: op
