name: Landlord
main: com.jcdesimp.landlord.Landlord
version: 0.1

commands:
   land:
      description: The base Landlord command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>